//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: stepmgr_rpc.proto

package stepmgr

import (
	metadata "git.code.oa.com/gongyi/donate_steps/api/metadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetPkInteractRequest_InteractType int32

const (
	SetPkInteractRequest_NO_INTERACT SetPkInteractRequest_InteractType = 0
	SetPkInteractRequest_THUMB       SetPkInteractRequest_InteractType = 1
	SetPkInteractRequest_SMILE       SetPkInteractRequest_InteractType = 2
	SetPkInteractRequest_BOMB        SetPkInteractRequest_InteractType = 3
)

// Enum value maps for SetPkInteractRequest_InteractType.
var (
	SetPkInteractRequest_InteractType_name = map[int32]string{
		0: "NO_INTERACT",
		1: "THUMB",
		2: "SMILE",
		3: "BOMB",
	}
	SetPkInteractRequest_InteractType_value = map[string]int32{
		"NO_INTERACT": 0,
		"THUMB":       1,
		"SMILE":       2,
		"BOMB":        3,
	}
)

func (x SetPkInteractRequest_InteractType) Enum() *SetPkInteractRequest_InteractType {
	p := new(SetPkInteractRequest_InteractType)
	*p = x
	return p
}

func (x SetPkInteractRequest_InteractType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetPkInteractRequest_InteractType) Descriptor() protoreflect.EnumDescriptor {
	return file_stepmgr_rpc_proto_enumTypes[0].Descriptor()
}

func (SetPkInteractRequest_InteractType) Type() protoreflect.EnumType {
	return &file_stepmgr_rpc_proto_enumTypes[0]
}

func (x SetPkInteractRequest_InteractType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetPkInteractRequest_InteractType.Descriptor instead.
func (SetPkInteractRequest_InteractType) EnumDescriptor() ([]byte, []int) {
	return file_stepmgr_rpc_proto_rawDescGZIP(), []int{8, 0}
}

type SetPkInteractRequest_InteractOps int32

const (
	SetPkInteractRequest_NO_OPS SetPkInteractRequest_InteractOps = 0
	SetPkInteractRequest_PLUS   SetPkInteractRequest_InteractOps = 1
	SetPkInteractRequest_MINUS  SetPkInteractRequest_InteractOps = 2
)

// Enum value maps for SetPkInteractRequest_InteractOps.
var (
	SetPkInteractRequest_InteractOps_name = map[int32]string{
		0: "NO_OPS",
		1: "PLUS",
		2: "MINUS",
	}
	SetPkInteractRequest_InteractOps_value = map[string]int32{
		"NO_OPS": 0,
		"PLUS":   1,
		"MINUS":  2,
	}
)

func (x SetPkInteractRequest_InteractOps) Enum() *SetPkInteractRequest_InteractOps {
	p := new(SetPkInteractRequest_InteractOps)
	*p = x
	return p
}

func (x SetPkInteractRequest_InteractOps) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetPkInteractRequest_InteractOps) Descriptor() protoreflect.EnumDescriptor {
	return file_stepmgr_rpc_proto_enumTypes[1].Descriptor()
}

func (SetPkInteractRequest_InteractOps) Type() protoreflect.EnumType {
	return &file_stepmgr_rpc_proto_enumTypes[1]
}

func (x SetPkInteractRequest_InteractOps) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetPkInteractRequest_InteractOps.Descriptor instead.
func (SetPkInteractRequest_InteractOps) EnumDescriptor() ([]byte, []int) {
	return file_stepmgr_rpc_proto_rawDescGZIP(), []int{8, 1}
}

type GetUsersStepsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIds   []string `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	RangeFlag bool     `protobuf:"varint,2,opt,name=range_flag,json=rangeFlag,proto3" json:"range_flag,omitempty"` // if set range flag, startTime & endTime must be set
	StartTime string   `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   string   `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (x *GetUsersStepsRequest) Reset() {
	*x = GetUsersStepsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stepmgr_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersStepsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersStepsRequest) ProtoMessage() {}

func (x *GetUsersStepsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stepmgr_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersStepsRequest.ProtoReflect.Descriptor instead.
func (*GetUsersStepsRequest) Descriptor() ([]byte, []int) {
	return file_stepmgr_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *GetUsersStepsRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *GetUsersStepsRequest) GetRangeFlag() bool {
	if x != nil {
		return x.RangeFlag
	}
	return false
}

func (x *GetUsersStepsRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *GetUsersStepsRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type GetUsersStepsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *metadata.CommonHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	UserStep map[string]*metadata.UserSteps `protobuf:"bytes,2,rep,name=user_step,json=userStep,proto3" json:"user_step,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetUsersStepsResponse) Reset() {
	*x = GetUsersStepsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stepmgr_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersStepsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersStepsResponse) ProtoMessage() {}

func (x *GetUsersStepsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stepmgr_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersStepsResponse.ProtoReflect.Descriptor instead.
func (*GetUsersStepsResponse) Descriptor() ([]byte, []int) {
	return file_stepmgr_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetUsersStepsResponse) GetHeader() *metadata.CommonHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetUsersStepsResponse) GetUserStep() map[string]*metadata.UserSteps {
	if x != nil {
		return x.UserStep
	}
	return nil
}

type SetUsersStepsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserStep   map[string]*metadata.UserSteps `protobuf:"bytes,1,rep,name=user_step,json=userStep,proto3" json:"user_step,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Background bool                           `protobuf:"varint,2,opt,name=background,proto3" json:"background,omitempty"` // background call
}

func (x *SetUsersStepsRequest) Reset() {
	*x = SetUsersStepsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stepmgr_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUsersStepsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUsersStepsRequest) ProtoMessage() {}

func (x *SetUsersStepsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stepmgr_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUsersStepsRequest.ProtoReflect.Descriptor instead.
func (*SetUsersStepsRequest) Descriptor() ([]byte, []int) {
	return file_stepmgr_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *SetUsersStepsRequest) GetUserStep() map[string]*metadata.UserSteps {
	if x != nil {
		return x.UserStep
	}
	return nil
}

func (x *SetUsersStepsRequest) GetBackground() bool {
	if x != nil {
		return x.Background
	}
	return false
}

type SetUsersStepsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *metadata.CommonHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *SetUsersStepsResponse) Reset() {
	*x = SetUsersStepsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stepmgr_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUsersStepsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUsersStepsResponse) ProtoMessage() {}

func (x *SetUsersStepsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stepmgr_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUsersStepsResponse.ProtoReflect.Descriptor instead.
func (*SetUsersStepsResponse) Descriptor() ([]byte, []int) {
	return file_stepmgr_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *SetUsersStepsResponse) GetHeader() *metadata.CommonHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type GetUsersPkProfileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIds []string `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
}

func (x *GetUsersPkProfileRequest) Reset() {
	*x = GetUsersPkProfileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stepmgr_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersPkProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersPkProfileRequest) ProtoMessage() {}

func (x *GetUsersPkProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stepmgr_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersPkProfileRequest.ProtoReflect.Descriptor instead.
func (*GetUsersPkProfileRequest) Descriptor() ([]byte, []int) {
	return file_stepmgr_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *GetUsersPkProfileRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetUsersPkProfileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header  *metadata.CommonHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Profile map[string]*metadata.UserPKProfile `protobuf:"bytes,2,rep,name=profile,proto3" json:"profile,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetUsersPkProfileResponse) Reset() {
	*x = GetUsersPkProfileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stepmgr_rpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersPkProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersPkProfileResponse) ProtoMessage() {}

func (x *GetUsersPkProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stepmgr_rpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersPkProfileResponse.ProtoReflect.Descriptor instead.
func (*GetUsersPkProfileResponse) Descriptor() ([]byte, []int) {
	return file_stepmgr_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *GetUsersPkProfileResponse) GetHeader() *metadata.CommonHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetUsersPkProfileResponse) GetProfile() map[string]*metadata.UserPKProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type GetPkInteractRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ToUserId string `protobuf:"bytes,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
}

func (x *GetPkInteractRequest) Reset() {
	*x = GetPkInteractRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stepmgr_rpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPkInteractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPkInteractRequest) ProtoMessage() {}

func (x *GetPkInteractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stepmgr_rpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPkInteractRequest.ProtoReflect.Descriptor instead.
func (*GetPkInteractRequest) Descriptor() ([]byte, []int) {
	return file_stepmgr_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *GetPkInteractRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPkInteractRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

type GetPkInteractResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//
	//enum TodayOps {
	//NO_INTERACT = 0;
	//THUMB = 1;
	//SMILE = 2;
	//BOMB = 3;
	//}
	Header  *metadata.CommonHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Profile *metadata.UserPKProfile `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"` //TodayOps todayOps = 2;
}

func (x *GetPkInteractResponse) Reset() {
	*x = GetPkInteractResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stepmgr_rpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPkInteractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPkInteractResponse) ProtoMessage() {}

func (x *GetPkInteractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stepmgr_rpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPkInteractResponse.ProtoReflect.Descriptor instead.
func (*GetPkInteractResponse) Descriptor() ([]byte, []int) {
	return file_stepmgr_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *GetPkInteractResponse) GetHeader() *metadata.CommonHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetPkInteractResponse) GetProfile() *metadata.UserPKProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type SetPkInteractRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string                            `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ToUserId string                            `protobuf:"bytes,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Interact SetPkInteractRequest_InteractType `protobuf:"varint,3,opt,name=interact,proto3,enum=stepmgr.SetPkInteractRequest_InteractType" json:"interact,omitempty"`
	Ops      SetPkInteractRequest_InteractOps  `protobuf:"varint,4,opt,name=ops,proto3,enum=stepmgr.SetPkInteractRequest_InteractOps" json:"ops,omitempty"`
}

func (x *SetPkInteractRequest) Reset() {
	*x = SetPkInteractRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stepmgr_rpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPkInteractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPkInteractRequest) ProtoMessage() {}

func (x *SetPkInteractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stepmgr_rpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPkInteractRequest.ProtoReflect.Descriptor instead.
func (*SetPkInteractRequest) Descriptor() ([]byte, []int) {
	return file_stepmgr_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *SetPkInteractRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetPkInteractRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *SetPkInteractRequest) GetInteract() SetPkInteractRequest_InteractType {
	if x != nil {
		return x.Interact
	}
	return SetPkInteractRequest_NO_INTERACT
}

func (x *SetPkInteractRequest) GetOps() SetPkInteractRequest_InteractOps {
	if x != nil {
		return x.Ops
	}
	return SetPkInteractRequest_NO_OPS
}

type SetPkInteractResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *metadata.CommonHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Result int32                  `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SetPkInteractResponse) Reset() {
	*x = SetPkInteractResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stepmgr_rpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPkInteractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPkInteractResponse) ProtoMessage() {}

func (x *SetPkInteractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stepmgr_rpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPkInteractResponse.ProtoReflect.Descriptor instead.
func (*SetPkInteractResponse) Descriptor() ([]byte, []int) {
	return file_stepmgr_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *SetPkInteractResponse) GetHeader() *metadata.CommonHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SetPkInteractResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type SetActivePkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ToUserId string `protobuf:"bytes,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
}

func (x *SetActivePkRequest) Reset() {
	*x = SetActivePkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stepmgr_rpc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetActivePkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActivePkRequest) ProtoMessage() {}

func (x *SetActivePkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stepmgr_rpc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActivePkRequest.ProtoReflect.Descriptor instead.
func (*SetActivePkRequest) Descriptor() ([]byte, []int) {
	return file_stepmgr_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *SetActivePkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetActivePkRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

type SetActivePkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *metadata.CommonHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Result int32                  `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SetActivePkResponse) Reset() {
	*x = SetActivePkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stepmgr_rpc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetActivePkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActivePkResponse) ProtoMessage() {}

func (x *SetActivePkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stepmgr_rpc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActivePkResponse.ProtoReflect.Descriptor instead.
func (*SetActivePkResponse) Descriptor() ([]byte, []int) {
	return file_stepmgr_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *SetActivePkResponse) GetHeader() *metadata.CommonHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SetActivePkResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type SetResponsePkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ToUserId string `protobuf:"bytes,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
}

func (x *SetResponsePkRequest) Reset() {
	*x = SetResponsePkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stepmgr_rpc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetResponsePkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponsePkRequest) ProtoMessage() {}

func (x *SetResponsePkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stepmgr_rpc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponsePkRequest.ProtoReflect.Descriptor instead.
func (*SetResponsePkRequest) Descriptor() ([]byte, []int) {
	return file_stepmgr_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *SetResponsePkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetResponsePkRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

type SetResponsePkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *metadata.CommonHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Result int32                  `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SetResponsePkResponse) Reset() {
	*x = SetResponsePkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stepmgr_rpc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetResponsePkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponsePkResponse) ProtoMessage() {}

func (x *SetResponsePkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stepmgr_rpc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponsePkResponse.ProtoReflect.Descriptor instead.
func (*SetResponsePkResponse) Descriptor() ([]byte, []int) {
	return file_stepmgr_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *SetResponsePkResponse) GetHeader() *metadata.CommonHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SetResponsePkResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type GetPassivePkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetPassivePkRequest) Reset() {
	*x = GetPassivePkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stepmgr_rpc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPassivePkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPassivePkRequest) ProtoMessage() {}

func (x *GetPassivePkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stepmgr_rpc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPassivePkRequest.ProtoReflect.Descriptor instead.
func (*GetPassivePkRequest) Descriptor() ([]byte, []int) {
	return file_stepmgr_rpc_proto_rawDescGZIP(), []int{14}
}

func (x *GetPassivePkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPassivePkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header  *metadata.CommonHeader    `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	History []*metadata.UserPKHistory `protobuf:"bytes,2,rep,name=history,proto3" json:"history,omitempty"`
}

func (x *GetPassivePkResponse) Reset() {
	*x = GetPassivePkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stepmgr_rpc_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPassivePkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPassivePkResponse) ProtoMessage() {}

func (x *GetPassivePkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stepmgr_rpc_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPassivePkResponse.ProtoReflect.Descriptor instead.
func (*GetPassivePkResponse) Descriptor() ([]byte, []int) {
	return file_stepmgr_rpc_proto_rawDescGZIP(), []int{15}
}

func (x *GetPassivePkResponse) GetHeader() *metadata.CommonHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetPassivePkResponse) GetHistory() []*metadata.UserPKHistory {
	if x != nil {
		return x.History
	}
	return nil
}

type GetPkNotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetPkNotificationRequest) Reset() {
	*x = GetPkNotificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stepmgr_rpc_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPkNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPkNotificationRequest) ProtoMessage() {}

func (x *GetPkNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stepmgr_rpc_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPkNotificationRequest.ProtoReflect.Descriptor instead.
func (*GetPkNotificationRequest) Descriptor() ([]byte, []int) {
	return file_stepmgr_rpc_proto_rawDescGZIP(), []int{16}
}

func (x *GetPkNotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPkNotificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header  *metadata.CommonHeader    `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	History []*metadata.UserPKHistory `protobuf:"bytes,2,rep,name=history,proto3" json:"history,omitempty"`
}

func (x *GetPkNotificationResponse) Reset() {
	*x = GetPkNotificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stepmgr_rpc_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPkNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPkNotificationResponse) ProtoMessage() {}

func (x *GetPkNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stepmgr_rpc_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPkNotificationResponse.ProtoReflect.Descriptor instead.
func (*GetPkNotificationResponse) Descriptor() ([]byte, []int) {
	return file_stepmgr_rpc_proto_rawDescGZIP(), []int{17}
}

func (x *GetPkNotificationResponse) GetHeader() *metadata.CommonHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetPkNotificationResponse) GetHistory() []*metadata.UserPKHistory {
	if x != nil {
		return x.History
	}
	return nil
}

var File_stepmgr_rpc_proto protoreflect.FileDescriptor

var file_stepmgr_rpc_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x74, 0x65, 0x70, 0x6d, 0x67, 0x72, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x74, 0x65, 0x70, 0x6d, 0x67, 0x72, 0x1a, 0x11, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x8a, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x53, 0x74, 0x65, 0x70,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x66, 0x6c, 0x61,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x6c,
	0x61, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xe4, 0x01, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x53, 0x74, 0x65, 0x70, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x49, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73,
	0x74, 0x65, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x73, 0x74, 0x65, 0x70,
	0x6d, 0x67, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x53, 0x74, 0x65, 0x70,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74,
	0x65, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x53, 0x74, 0x65,
	0x70, 0x1a, 0x50, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x65, 0x70, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x74, 0x65, 0x70, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0xd2, 0x01, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x53, 0x74, 0x65, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x48, 0x0a, 0x09,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x65, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2b, 0x2e, 0x73, 0x74, 0x65, 0x70, 0x6d, 0x67, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x53, 0x74, 0x65, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x74, 0x65, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x53, 0x74, 0x65, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x62, 0x61, 0x63, 0x6b,
	0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x1a, 0x50, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74,
	0x65, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x65, 0x70, 0x73, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x47, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x53, 0x74, 0x65, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2e, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x22, 0x35, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x50, 0x6b, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x22, 0xeb, 0x01, 0x0a, 0x19, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x50, 0x6b, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x49, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x73, 0x74, 0x65, 0x70, 0x6d, 0x67,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x50, 0x6b, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x1a, 0x53, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x2d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x50, 0x4b, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x4d, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x6b, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x0a, 0x74, 0x6f, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x7a, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x6b, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e,
	0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x31,
	0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50,
	0x4b, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x22, 0xc3, 0x02, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x50, 0x6b, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x0a, 0x74, 0x6f, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x46, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x73, 0x74, 0x65, 0x70, 0x6d, 0x67, 0x72, 0x2e, 0x53, 0x65,
	0x74, 0x50, 0x6b, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x12, 0x3b, 0x0a, 0x03, 0x6f, 0x70, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x73, 0x74, 0x65, 0x70, 0x6d, 0x67, 0x72,
	0x2e, 0x53, 0x65, 0x74, 0x50, 0x6b, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x4f, 0x70,
	0x73, 0x52, 0x03, 0x6f, 0x70, 0x73, 0x22, 0x3f, 0x0a, 0x0c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61,
	0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x4f, 0x5f, 0x49, 0x4e, 0x54,
	0x45, 0x52, 0x41, 0x43, 0x54, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x48, 0x55, 0x4d, 0x42,
	0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x4d, 0x49, 0x4c, 0x45, 0x10, 0x02, 0x12, 0x08, 0x0a,
	0x04, 0x42, 0x4f, 0x4d, 0x42, 0x10, 0x03, 0x22, 0x2e, 0x0a, 0x0b, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x61, 0x63, 0x74, 0x4f, 0x70, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x5f, 0x4f, 0x50, 0x53,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x4c, 0x55, 0x53, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x4d, 0x49, 0x4e, 0x55, 0x53, 0x10, 0x02, 0x22, 0x5f, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x50, 0x6b,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2e, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x4b, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x50, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x0a, 0x74, 0x6f, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x5d, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x50, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x4d, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x50, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x0a, 0x74, 0x6f, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x5f, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x50, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x2e, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x69,
	0x76, 0x65, 0x50, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x79, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x69,
	0x76, 0x65, 0x50, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x07,
	0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x4b, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x22,
	0x33, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x50, 0x6b, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x7e, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x50, 0x6b, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2e, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x31, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x50, 0x4b, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x07, 0x68, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x2e, 0x63, 0x6f, 0x64, 0x65,
	0x2e, 0x6f, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6e, 0x67, 0x79, 0x69, 0x2f, 0x64,
	0x6f, 0x6e, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x74, 0x65, 0x70, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x73, 0x74, 0x65, 0x70, 0x6d, 0x67, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stepmgr_rpc_proto_rawDescOnce sync.Once
	file_stepmgr_rpc_proto_rawDescData = file_stepmgr_rpc_proto_rawDesc
)

func file_stepmgr_rpc_proto_rawDescGZIP() []byte {
	file_stepmgr_rpc_proto_rawDescOnce.Do(func() {
		file_stepmgr_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_stepmgr_rpc_proto_rawDescData)
	})
	return file_stepmgr_rpc_proto_rawDescData
}

var file_stepmgr_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_stepmgr_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_stepmgr_rpc_proto_goTypes = []interface{}{
	(SetPkInteractRequest_InteractType)(0), // 0: stepmgr.SetPkInteractRequest.InteractType
	(SetPkInteractRequest_InteractOps)(0),  // 1: stepmgr.SetPkInteractRequest.InteractOps
	(*GetUsersStepsRequest)(nil),           // 2: stepmgr.GetUsersStepsRequest
	(*GetUsersStepsResponse)(nil),          // 3: stepmgr.GetUsersStepsResponse
	(*SetUsersStepsRequest)(nil),           // 4: stepmgr.SetUsersStepsRequest
	(*SetUsersStepsResponse)(nil),          // 5: stepmgr.SetUsersStepsResponse
	(*GetUsersPkProfileRequest)(nil),       // 6: stepmgr.GetUsersPkProfileRequest
	(*GetUsersPkProfileResponse)(nil),      // 7: stepmgr.GetUsersPkProfileResponse
	(*GetPkInteractRequest)(nil),           // 8: stepmgr.GetPkInteractRequest
	(*GetPkInteractResponse)(nil),          // 9: stepmgr.GetPkInteractResponse
	(*SetPkInteractRequest)(nil),           // 10: stepmgr.SetPkInteractRequest
	(*SetPkInteractResponse)(nil),          // 11: stepmgr.SetPkInteractResponse
	(*SetActivePkRequest)(nil),             // 12: stepmgr.SetActivePkRequest
	(*SetActivePkResponse)(nil),            // 13: stepmgr.SetActivePkResponse
	(*SetResponsePkRequest)(nil),           // 14: stepmgr.SetResponsePkRequest
	(*SetResponsePkResponse)(nil),          // 15: stepmgr.SetResponsePkResponse
	(*GetPassivePkRequest)(nil),            // 16: stepmgr.GetPassivePkRequest
	(*GetPassivePkResponse)(nil),           // 17: stepmgr.GetPassivePkResponse
	(*GetPkNotificationRequest)(nil),       // 18: stepmgr.GetPkNotificationRequest
	(*GetPkNotificationResponse)(nil),      // 19: stepmgr.GetPkNotificationResponse
	nil,                                    // 20: stepmgr.GetUsersStepsResponse.UserStepEntry
	nil,                                    // 21: stepmgr.SetUsersStepsRequest.UserStepEntry
	nil,                                    // 22: stepmgr.GetUsersPkProfileResponse.ProfileEntry
	(*metadata.CommonHeader)(nil),          // 23: metadata.CommonHeader
	(*metadata.UserPKProfile)(nil),         // 24: metadata.UserPKProfile
	(*metadata.UserPKHistory)(nil),         // 25: metadata.UserPKHistory
	(*metadata.UserSteps)(nil),             // 26: metadata.UserSteps
}
var file_stepmgr_rpc_proto_depIdxs = []int32{
	23, // 0: stepmgr.GetUsersStepsResponse.header:type_name -> metadata.CommonHeader
	20, // 1: stepmgr.GetUsersStepsResponse.user_step:type_name -> stepmgr.GetUsersStepsResponse.UserStepEntry
	21, // 2: stepmgr.SetUsersStepsRequest.user_step:type_name -> stepmgr.SetUsersStepsRequest.UserStepEntry
	23, // 3: stepmgr.SetUsersStepsResponse.header:type_name -> metadata.CommonHeader
	23, // 4: stepmgr.GetUsersPkProfileResponse.header:type_name -> metadata.CommonHeader
	22, // 5: stepmgr.GetUsersPkProfileResponse.profile:type_name -> stepmgr.GetUsersPkProfileResponse.ProfileEntry
	23, // 6: stepmgr.GetPkInteractResponse.header:type_name -> metadata.CommonHeader
	24, // 7: stepmgr.GetPkInteractResponse.profile:type_name -> metadata.UserPKProfile
	0,  // 8: stepmgr.SetPkInteractRequest.interact:type_name -> stepmgr.SetPkInteractRequest.InteractType
	1,  // 9: stepmgr.SetPkInteractRequest.ops:type_name -> stepmgr.SetPkInteractRequest.InteractOps
	23, // 10: stepmgr.SetPkInteractResponse.header:type_name -> metadata.CommonHeader
	23, // 11: stepmgr.SetActivePkResponse.header:type_name -> metadata.CommonHeader
	23, // 12: stepmgr.SetResponsePkResponse.header:type_name -> metadata.CommonHeader
	23, // 13: stepmgr.GetPassivePkResponse.header:type_name -> metadata.CommonHeader
	25, // 14: stepmgr.GetPassivePkResponse.history:type_name -> metadata.UserPKHistory
	23, // 15: stepmgr.GetPkNotificationResponse.header:type_name -> metadata.CommonHeader
	25, // 16: stepmgr.GetPkNotificationResponse.history:type_name -> metadata.UserPKHistory
	26, // 17: stepmgr.GetUsersStepsResponse.UserStepEntry.value:type_name -> metadata.UserSteps
	26, // 18: stepmgr.SetUsersStepsRequest.UserStepEntry.value:type_name -> metadata.UserSteps
	24, // 19: stepmgr.GetUsersPkProfileResponse.ProfileEntry.value:type_name -> metadata.UserPKProfile
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_stepmgr_rpc_proto_init() }
func file_stepmgr_rpc_proto_init() {
	if File_stepmgr_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stepmgr_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersStepsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stepmgr_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersStepsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stepmgr_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUsersStepsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stepmgr_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUsersStepsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stepmgr_rpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersPkProfileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stepmgr_rpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersPkProfileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stepmgr_rpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPkInteractRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stepmgr_rpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPkInteractResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stepmgr_rpc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPkInteractRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stepmgr_rpc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPkInteractResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stepmgr_rpc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetActivePkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stepmgr_rpc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetActivePkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stepmgr_rpc_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetResponsePkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stepmgr_rpc_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetResponsePkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stepmgr_rpc_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPassivePkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stepmgr_rpc_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPassivePkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stepmgr_rpc_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPkNotificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stepmgr_rpc_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPkNotificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stepmgr_rpc_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stepmgr_rpc_proto_goTypes,
		DependencyIndexes: file_stepmgr_rpc_proto_depIdxs,
		EnumInfos:         file_stepmgr_rpc_proto_enumTypes,
		MessageInfos:      file_stepmgr_rpc_proto_msgTypes,
	}.Build()
	File_stepmgr_rpc_proto = out.File
	file_stepmgr_rpc_proto_rawDesc = nil
	file_stepmgr_rpc_proto_goTypes = nil
	file_stepmgr_rpc_proto_depIdxs = nil
}
